/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package publicLoginPage;

import deviceListener.CustomDragListener;
import java.awt.EventQueue;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author rafikhan
 */
public class SearchPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public SearchPage() {
        initComponents();
        jComboBox1.setLightWeightPopupEnabled(false);
        jComboBox2.setLightWeightPopupEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLeft = new javax.swing.JPanel();
        jPanelSearch = new javax.swing.JPanel();
        jPanelSearchFields = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        checkbox1 = new java.awt.Checkbox();
        jLabel3 = new javax.swing.JLabel();
        datePicker3 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        jPanelLeft.setBackground(new java.awt.Color(0, 153, 153));

        jPanelSearch.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSearchFields.setBackground(new java.awt.Color(255, 204, 204));
        jPanelSearchFields.setLayout(new java.awt.GridLayout(5, 2, 1, 2));

        jLabel1.setText("Destination City");
        jPanelSearchFields.add(jLabel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelSearchFields.add(jComboBox1);

        jLabel2.setText("Depart City");
        jPanelSearchFields.add(jLabel2);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelSearchFields.add(jComboBox2);

        jLabel4.setText("AC / non-AC");
        jPanelSearchFields.add(jLabel4);
        jPanelSearchFields.add(checkbox1);

        jLabel3.setText("Day Of Travel");
        jPanelSearchFields.add(jLabel3);
        jPanelSearchFields.add(datePicker3);

        jLabel5.setText("Person");
        jPanelSearchFields.add(jLabel5);
        jPanelSearchFields.add(jSpinner1);

        jPanelSearch.add(jPanelSearchFields, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 60, 270, 120));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelSearch.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 110, -1));

        jLabel12.setText("Search");
        jPanelSearch.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 110, 30));

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelLeft);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //data validation
        if(true){
            new SearchResult(this).setVisible(true);
            dispose();
        }else{
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkbox1;
    private com.github.lgooddatepicker.components.DatePicker datePicker3;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JPanel jPanelSearchFields;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
